import { createServer, type Server } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { expect, test } from "playwright/test";
import { startLocalApiServer } from "../../src/main/local-api";

test("safe live run shows a disconnected projection without raw event payload", async ({ page }) => { const renderer = await serve(); const api = await startLocalApiServer({ allowedOrigin: origin(renderer), capability: "cap", runProjection: () => ({ status: "disconnected", elapsedMs: 2, step: "inspecting" }) }); if (api._tag !== "started") throw new Error("api"); try { await page.addInitScript(({ baseUrl }) => Object.defineProperty(window, "patchdesk", { value: { localApi: { baseUrl, capability: "cap" } } }), { baseUrl: api.server.url.toString() }); await page.goto(`${origin(renderer)}/#run-fixture`); await expect(page.getByText("Run status: disconnected")).toBeVisible(); await expect(page.getByText(/prompt|toolCall|thinking/i)).toHaveCount(0); await page.screenshot({ path: "test-results/milestone-8-browser.png", fullPage: true }); } finally { await api.server.stop(); await close(renderer); } });
async function serve(): Promise<Server> { const root = join(process.cwd(), "out/renderer"); const server = createServer(async (request, response) => { const file = normalize(join(root, request.url === undefined || request.url === "/" ? "index.html" : request.url)); try { response.writeHead(200, { "Content-Type": extname(file) === ".js" ? "text/javascript" : extname(file) === ".css" ? "text/css" : "text/html" }).end(await readFile(file)); } catch { response.writeHead(404).end(); } }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); return server; }
function origin(server: Server): string { const value = server.address(); if (value === null || typeof value === "string") throw new Error("address"); return `http://127.0.0.1:${value.port}`; }
function close(server: Server): Promise<void> { return new Promise((resolve, reject) => server.close((error) => error === undefined ? resolve() : reject(error))); }
