import { describe, expect, it } from "vitest";

import {
  changeScopeFromPatch,
  changeScopeSegments,
  classifyChangedPath,
  computeChangeScope,
  type ChangeScopeBucket,
} from "../../src/domain/change-scope";

const pathCases: ReadonlyArray<{
  readonly path: string;
  readonly bucket: ChangeScopeBucket;
}> = [
  { path: "src/domain/change-scope.ts", bucket: "core" },
  { path: "src/renderer/src/components/scope-gauge.tsx", bucket: "core" },
  { path: "src/main/local-api.ts", bucket: "core" },
  { path: "Makefile", bucket: "core" },
  { path: "src/adapters/storage/fixtures.ts", bucket: "core" },
  { path: "pnpm-lock.yaml", bucket: "generated" },
  { path: "package-lock.json", bucket: "generated" },
  { path: "yarn.lock", bucket: "generated" },
  { path: "Cargo.lock", bucket: "generated" },
  { path: "go.sum", bucket: "generated" },
  { path: "src/domain/schema.generated.ts", bucket: "generated" },
  {
    path: "tests/renderer/__snapshots__/app.ui.test.tsx.snap",
    bucket: "generated",
  },
  { path: "src/domain/inline.snap", bucket: "generated" },
  { path: "docs/api-report.api.md", bucket: "generated" },
  { path: "tests/domain/change-scope.test.ts", bucket: "tests" },
  { path: "test/helpers.ts", bucket: "tests" },
  { path: "src/domain/__tests__/patch.ts", bucket: "tests" },
  { path: "src/domain/patch.spec.ts", bucket: "tests" },
  { path: "e2e/review.ts", bucket: "tests" },
  { path: "fixtures/patch.txt", bucket: "tests" },
  { path: "internal/cache/refresh_cache_test.go", bucket: "tests" },
  { path: "src/store/repository_test.rs", bucket: "tests" },
  { path: "lib/parser_test.cc", bucket: "tests" },
  { path: "app/test_repository.py", bucket: "tests" },
  { path: "app/repository_test.py", bucket: "tests" },
  { path: "src/main/java/com/acme/RepositoryTest.java", bucket: "tests" },
  { path: "src/main/kotlin/com/acme/RepositoryTests.kt", bucket: "tests" },
  { path: "Sources/AcmeTests.swift", bucket: "tests" },
  { path: "src/Acme/RepositoryTest.php", bucket: "tests" },
  { path: "src/Acme/RepositoryTests.cs", bucket: "tests" },
  { path: "lib/acme/repository_spec.rb", bucket: "tests" },
  { path: "lib/acme/repository_test.rb", bucket: "tests" },
  { path: "lib/acme/repository_test.exs", bucket: "tests" },
  // A source file whose name merely ends in "test" is not a test file.
  { path: "src/domain/latest.ts", bucket: "core" },
  { path: "src/domain/protest.go", bucket: "core" },
  { path: "docs/architecture.md", bucket: "docs" },
  { path: "docs/adr/0012-insight.md", bucket: "docs" },
  { path: "README.mdx", bucket: "docs" },
  { path: "CHANGELOG.md", bucket: "docs" },
  { path: "LICENSE", bucket: "docs" },
  { path: ".gitattributes", bucket: "config" },
  { path: ".github/workflows/gates.yml", bucket: "config" },
  { path: "scripts/lint-staged-lib.mjs", bucket: "config" },
  { path: "tsconfig.scripts.json", bucket: "config" },
  { path: "electron.vite.config.ts", bucket: "config" },
  { path: "knip.json", bucket: "config" },
  { path: "resources/theme.toml", bucket: "config" },
  // A data file under `src/` is source, not repository configuration.
  { path: "src/adapters/github/wire.json", bucket: "core" },
];

describe("classifyChangedPath", () => {
  for (const testCase of pathCases) {
    it(`puts ${testCase.path} in ${testCase.bucket}`, () => {
      expect(
        classifyChangedPath({
          path: testCase.path,
          additions: 0,
          deletions: 0,
        }),
      ).toBe(testCase.bucket);
    });
  }

  it("prefers generated over every later rule", () => {
    expect(
      classifyChangedPath({
        path: "tests/domain/table.generated.test.ts",
        additions: 1,
        deletions: 0,
      }),
    ).toBe("generated");
  });

  it("reads a generated banner only from the first three lines", () => {
    const banner = (line: number): string =>
      `${"// header\n".repeat(line - 1)}// @generated by a tool\n`;
    expect(
      classifyChangedPath({
        path: "src/domain/wire.ts",
        additions: 1,
        deletions: 0,
        head: banner(3),
      }),
    ).toBe("generated");
    expect(
      classifyChangedPath({
        path: "src/domain/wire.ts",
        additions: 1,
        deletions: 0,
        head: banner(4),
      }),
    ).toBe("core");
  });

  it("treats a path .gitattributes marked linguist-generated as generated", () => {
    expect(
      classifyChangedPath(
        { path: "src/domain/wire.ts", additions: 1, deletions: 0 },
        { generatedPaths: ["src/domain/wire.ts"] },
      ),
    ).toBe("generated");
  });
});

describe("computeChangeScope", () => {
  it("sums each bucket and omits the buckets no file reached", () => {
    const scope = computeChangeScope([
      { path: "src/domain/a.ts", additions: 10, deletions: 2 },
      { path: "src/domain/b.ts", additions: 5, deletions: 1 },
      { path: "tests/domain/a.test.ts", additions: 20, deletions: 0 },
      { path: "pnpm-lock.yaml", additions: 300, deletions: 100 },
    ]);
    expect(scope.buckets).toStrictEqual([
      { bucket: "core", files: 2, additions: 15, deletions: 3 },
      { bucket: "tests", files: 1, additions: 20, deletions: 0 },
      { bucket: "generated", files: 1, additions: 300, deletions: 100 },
    ]);
    expect(scope.total).toStrictEqual({
      files: 4,
      additions: 335,
      deletions: 103,
    });
  });

  it("returns an empty scope for no changed files", () => {
    expect(computeChangeScope([])).toStrictEqual({
      buckets: [],
      total: { files: 0, additions: 0, deletions: 0 },
    });
  });
});

describe("changeScopeSegments", () => {
  it("shares the whole bar out and never drops a bucket below its floor", () => {
    const segments = changeScopeSegments({
      buckets: [
        { bucket: "core", files: 2, additions: 15, deletions: 3 },
        { bucket: "tests", files: 1, additions: 20, deletions: 0 },
        { bucket: "generated", files: 1, additions: 300, deletions: 100 },
      ],
      total: { files: 4, additions: 335, deletions: 103 },
    });
    expect(segments.map((segment) => segment.bucket)).toStrictEqual([
      "core",
      "tests",
      "generated",
    ]);
    expect(
      segments.reduce((running, segment) => running + segment.percent, 0),
    ).toBeCloseTo(100);
    for (const segment of segments) expect(segment.percent).toBeGreaterThan(1);
  });

  it("splits the bar evenly when no bucket changed a line", () => {
    expect(
      changeScopeSegments({
        buckets: [
          { bucket: "core", files: 1, additions: 0, deletions: 0 },
          { bucket: "docs", files: 1, additions: 0, deletions: 0 },
        ],
        total: { files: 2, additions: 0, deletions: 0 },
      }).map((segment) => segment.percent),
    ).toStrictEqual([50, 50]);
  });
});

describe("changeScopeFromPatch", () => {
  it("counts a unified patch's added and removed lines per bucket", () => {
    const patch = [
      "diff --git a/src/domain/a.ts b/src/domain/a.ts",
      "--- a/src/domain/a.ts",
      "+++ b/src/domain/a.ts",
      "@@ -1,2 +1,2 @@",
      " keep",
      "-old",
      "+new",
      "diff --git a/docs/guide.md b/docs/guide.md",
      "--- a/docs/guide.md",
      "+++ b/docs/guide.md",
      "@@ -1,1 +1,2 @@",
      " intro",
      "+added",
      "",
    ].join("\n");
    expect(changeScopeFromPatch(patch)).toStrictEqual({
      buckets: [
        { bucket: "core", files: 1, additions: 1, deletions: 1 },
        { bucket: "docs", files: 1, additions: 1, deletions: 0 },
      ],
      total: { files: 2, additions: 2, deletions: 1 },
    });
  });

  it("attributes a deleted file to the path it had", () => {
    const patch = [
      "diff --git a/src/domain/gone.ts b/src/domain/gone.ts",
      "deleted file mode 100644",
      "--- a/src/domain/gone.ts",
      "+++ /dev/null",
      "@@ -1,1 +0,0 @@",
      "-gone",
      "",
    ].join("\n");
    expect(changeScopeFromPatch(patch).buckets).toStrictEqual([
      { bucket: "core", files: 1, additions: 0, deletions: 1 },
    ]);
  });
});
